# Generated by Django 4.2.11 on 2024-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cer_images')),
                ('issuing_organization', models.CharField(max_length=255)),
                ('date_issued', models.DateField()),
            ],
        ),
    ]
